<script src="{{ '/frontend/js/vendor/jquery-3.6.0.min.js' }}"></script>
<script src="{{ '/frontend/js/vendor/modernizr-3.6.0.min.js' }}"></script>
<script src="{{ '/frontend/js/vendor/jquery-migrate-3.3.0.min.js' }}"></script>
<script src="{{ '/frontend/js/vendor/bootstrap.bundle.min.js' }}"></script>
<script src="{{ '/frontend/js/plugins/slick.js' }}"></script>
<script src="{{ '/frontend/js/plugins/jquery.syotimer.min.js' }}"></script>
<script src="{{ '/frontend/js/plugins/wow.js' }}"></script>
<script src="{{ '/frontend/js/plugins/jquery-ui.js' }}"></script>
<script src="{{ '/frontend/js/plugins/perfect-scrollbar.js' }}"></script>
<script src="{{ '/frontend/js/plugins/magnific-popup.js' }}"></script>
<script src="{{ '/frontend/js/plugins/select2.min.js' }}"></script>
<script src="{{ '/frontend/js/plugins/waypoints.js' }}"></script>
<script src="{{ '/frontend/js/plugins/counterup.js' }}"></script>
<script src="{{ '/frontend/js/plugins/jquery.countdown.min.js' }}"></script>
<script src="{{ '/frontend/js/plugins/images-loaded.js' }}"></script>
<script src="{{ '/frontend/js/plugins/isotope.js' }}"></script>
<script src="{{ '/frontend/js/plugins/scrollup.js' }}"></script>
<script src="{{ '/frontend/js/plugins/jquery.vticker-min.js' }}"></script>
<script src="{{ '/frontend/js/plugins/jquery.theia.sticky.js' }}"></script>
<script src="{{ '/frontend/js/plugins/jquery.elevatezoom.js' }}"></script>
<!-- Template  JS -->
<script src="{{ '/frontend/js/main.js?v=3.3' }}"></script>
<script src="{{ '/frontend/js/shop.js?v=3.3' }}"></script>
<script src="{{ '/frontend/js/custom.js' }}"></script>
<script src="{{ '/frontend/js/sweetalert.js' }}"></script>